# vim:ft=kitty
background #131318
foreground #e4e1e9
selection_background #3a4379
selection_foreground #dee0ff
url_color #bbc3ff
cursor #bbc3ff
cursor_text_color #131318
active_tab_background #bbc3ff
active_tab_foreground #232c61
inactive_tab_background #46464f
inactive_tab_foreground #c7c5d0
active_border_color #bbc3ff
inactive_border_color #46464f
color0 #131318
color1 #ffb4ab
color2 #e6bad7
color3 #c4c5dd
color4 #bbc3ff
color5 #434559
color6 #5d3c54
color7 #e4e1e9
color8 #46464f
color9 #ffb4ab
color10 #e6bad7
color11 #434559
color12 #3a4379
color13 #5d3c54
color14 #c4c5dd
color15 #c7c5d0

