import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("../../lock.qml", import.meta.url), "utf8");
const surfaceSource = await readFile(new URL("../../lock/LockSurface.qml", import.meta.url), "utf8");
const backgroundSource = await readFile(new URL("../../lock/LockBackground.qml", import.meta.url), "utf8");

assert.match(source, /Lock\.LockSurface\s*\{[\s\S]*?controller:\s*lockController\b/);
assert.match(source, /Lock\.LockController\s*\{\s*id:\s*lockController\b/);
assert.doesNotMatch(source, /controller:\s*controller\b/);
assert.match(surfaceSource, /TextInput\s*\{[\s\S]*?clip:\s*true\b/);
assert.match(surfaceSource, /onEnabledChanged:[\s\S]*?forceActiveFocus\(\)/);
assert.match(surfaceSource, /text: Qt\.formatTime\(new Date\(\), "h:mm"\)/);
assert.match(surfaceSource, /font\.pixelSize: 96/);
assert.match(surfaceSource, /font\.bold: false/);
assert.match(surfaceSource, /width: clock\.implicitWidth/);
assert.match(surfaceSource, /anchors\.horizontalCenter: parent\.horizontalCenter/);
assert.doesNotMatch(surfaceSource, /: "Enter password"/);
assert.match(surfaceSource, /statusMessage:[\s\S]*?state === "authenticating"[\s\S]*?authenticationSubmitted[\s\S]*?"Authenticating\.\.\."/);
assert.match(surfaceSource, /text: inputField\.statusMessage/);
assert.match(surfaceSource, /id: statusText/);
assert.match(surfaceSource, /visible: passwordInput\.text\.length === 0/);
assert.match(surfaceSource, /layer\.effect: DropShadow/);
assert.match(surfaceSource, /color: surface\.lockTheme\.tokens\.background/);
assert.equal((surfaceSource.match(/layer\.effect: DropShadow/g) || []).length, 2);
assert.match(surfaceSource, /color: surface\.lockTheme\.tokens\.background\s*\n\s*opacity: 0\.35/);
assert.match(surfaceSource, /state === "retryDelay"[\s\S]*?tokens\.error/);
assert.match(surfaceSource, /inputPending: passwordInput\.text\.length > 0/);
assert.match(surfaceSource, /inputPending:[\s\S]*?authenticationSubmitted/);
assert.match(surfaceSource, /inputPending[\s\S]*?tokens\.warning/);
assert.match(surfaceSource, /border\.color:[\s\S]*?tokens\.primary/);
assert.match(backgroundSource, /PreserveAspectCrop/);
assert.match(backgroundSource, /sourceSize: Qt\.size\(root\.maxImageWidth, root\.maxImageHeight\)/);
assert.match(backgroundSource, /asynchronous: false/);
assert.match(backgroundSource, /source: composition/);
assert.match(backgroundSource, /radius: 12/);
assert.match(backgroundSource, /samples: 25/);
assert.match(backgroundSource, /GradientStop \{ position: 0\.0; color: "#00000000" \}/);
assert.match(backgroundSource, /GradientStop \{ position: 1\.0; color: "#ff000000" \}/);

console.log("LOCK_ENTRY_TEST_PASSED");
