import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("../../lock.qml", import.meta.url), "utf8");
const surfaceSource = await readFile(new URL("../../lock/LockSurface.qml", import.meta.url), "utf8");
const backgroundSource = await readFile(new URL("../../lock/LockBackground.qml", import.meta.url), "utf8");
const powerSource = await readFile(new URL("../../lock/LockPowerReader.qml", import.meta.url), "utf8");

assert.match(source, /Lock\.LockSurface\s*\{[\s\S]*?controller:\s*lockController\b/);
assert.match(source, /Lock\.LockController\s*\{\s*id:\s*lockController\b/);
assert.match(source, /Lock\.LockPowerReader\s*\{\s*id:\s*powerReader\b/);
assert.match(source, /power:\s*powerReader\b/);
assert.match(source, /now:\s*root\.now\b/);
assert.match(source, /function scheduleClockUpdate\(\)/);
assert.match(source, /60000 - millisecondsIntoMinute/);
assert.doesNotMatch(source, /controller:\s*controller\b/);
assert.match(surfaceSource, /TextInput\s*\{[\s\S]*?clip:\s*true\b/);
assert.match(surfaceSource, /onEnabledChanged:[\s\S]*?forceActiveFocus\(\)/);
assert.match(surfaceSource, /text: Qt\.formatTime\(surface\.now, "h:mm"\)/);
assert.match(surfaceSource, /text: surface\.dayText\(surface\.now\)/);
assert.match(surfaceSource, /function ordinalDay\(day\)/);
assert.match(surfaceSource, /"September"/);
assert.match(surfaceSource, /font\.pixelSize: 149/);
assert.match(surfaceSource, /font\.pixelSize: 36/);
assert.match(surfaceSource, /font\.family: "Roboto"/);
assert.match(surfaceSource, /font\.weight: Font\.Bold/);
assert.match(surfaceSource, /id: clockFontMetrics[\s\S]*?font\.family: "Roboto"[\s\S]*?font\.pixelSize: 149/);
assert.match(surfaceSource, /id: batteryFontMetrics[\s\S]*?font\.pixelSize: 54/);
assert.match(surfaceSource, /anchors\.bottomMargin: Math\.max\(0, 60 - clockFontMetrics\.descent\)/);
assert.match(surfaceSource, /id: inputField\s*\n\s*anchors\.centerIn: parent/);
assert.match(surfaceSource, /width: 179\s*\n\s*height: 52/);
assert.match(surfaceSource, /anchors\.leftMargin: 60/);
assert.match(surfaceSource, /id: clock\s*\n\s*x: -clockTextMetrics\.tightBoundingRect\.x/);
assert.match(surfaceSource, /anchors\.bottomMargin: Math\.max\(0, 60 - clockFontMetrics\.descent\)/);
assert.match(surfaceSource, /anchors\.rightMargin: 60/);
assert.match(surfaceSource, /anchors\.bottomMargin: Math\.max\(0, 60 - batteryFontMetrics\.descent\)/);
assert.match(surfaceSource, /spacing: 4/);
assert.match(surfaceSource, /spacing: -18/);
assert.doesNotMatch(surfaceSource, /: "Enter password"/);
assert.match(surfaceSource, /statusMessage:[\s\S]*?state === "authenticating"[\s\S]*?authenticationSubmitted[\s\S]*?"Authenticating\.\.\."/);
assert.match(surfaceSource, /text: inputField\.statusMessage/);
assert.match(surfaceSource, /id: statusText/);
assert.match(surfaceSource, /visible: passwordInput\.text\.length === 0/);
assert.match(surfaceSource, /layer\.effect: DropShadow/);
assert.match(surfaceSource, /color: surface\.lockTheme\.tokens\.background/);
assert.equal((surfaceSource.match(/layer\.effect: DropShadow/g) || []).length, 3);
assert.match(surfaceSource, /color: surface\.lockTheme\.tokens\.background\s*\n\s*opacity: 0\.35/);
assert.match(surfaceSource, /state === "retryDelay"[\s\S]*?tokens\.error/);
assert.match(surfaceSource, /inputPending: passwordInput\.text\.length > 0/);
assert.match(surfaceSource, /inputPending:[\s\S]*?authenticationSubmitted/);
assert.match(surfaceSource, /inputPending[\s\S]*?tokens\.warning/);
assert.match(surfaceSource, /border\.color:[\s\S]*?tokens\.primary/);
assert.match(surfaceSource, /text: "battery_android_frame_full"/);
assert.match(surfaceSource, /text: `\$\{surface\.power\.percentage\}%`/);
assert.match(surfaceSource, /visible: surface\.power\.available/);
assert.match(powerSource, /import Quickshell\.Services\.UPower/);
assert.match(powerSource, /Math\.max\(0, Math\.min\(100, Math\.round\(device\.percentage \* 100\)\)\)/);
assert.match(backgroundSource, /PreserveAspectCrop/);
assert.match(backgroundSource, /sourceSize: Qt\.size\(root\.maxImageWidth, root\.maxImageHeight\)/);
assert.match(backgroundSource, /asynchronous: false/);
assert.match(backgroundSource, /source: composition/);
assert.match(backgroundSource, /radius: 12/);
assert.match(backgroundSource, /samples: 25/);
assert.match(backgroundSource, /GradientStop \{ position: 0\.0; color: "#00000000" \}/);
assert.match(backgroundSource, /GradientStop \{ position: 1\.0; color: "#ff000000" \}/);

console.log("LOCK_ENTRY_TEST_PASSED");
