import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { mapMatugenTheme } from "../../utils/Matugen.mjs";

const fixture = JSON.parse(await readFile(new URL("../fixtures/matugen/dark.json", import.meta.url), "utf8"));
const result = mapMatugenTheme(fixture, "dark");

assert.equal(result.ok, true, result.errors.join("; "));
assert.equal(result.value.id, "wallpaper");
assert.equal(result.value.tokens.surface_panel, "#ff101820");
assert.equal(result.value.tokens.surface_sidebar, "#0a0f14");
assert.equal(result.value.tokens.surface_low, "#0a0f14");
assert.equal(result.value.tokens.surface_variant, "#202b35");
assert.equal(result.value.tokens.surface_container_lowest, "#111c26");
assert.equal(result.value.tokens.surface_container_low, "#1c2731");
assert.equal(result.value.tokens.surface_container, "#202b35");
assert.equal(result.value.tokens.surface_container_high, "#29343e");
assert.equal(result.value.tokens.surface_container_highest, "#303b45");
assert.equal(result.value.tokens.surface_hover, "#34414c");
assert.equal(result.value.tokens.on_surface_subdued, "#d1dae4");
assert.equal(result.value.tokens.on_surface_indicator, "#f4f7fb");
assert.equal(result.value.tokens.on_surface_disabled, "#414b56");
const translucent = mapMatugenTheme(fixture, "dark", { kittyOpacity: 0.96, hyprlandActiveOpacity: 0.95 });
assert.equal(translucent.value.tokens.surface_panel, "#e9101820");
assert.equal(translucent.value.tokens.surface_sidebar, "#0a0f14");
assert.equal(translucent.value.tokens.surface_low, "#0a0f14");
assert.equal(mapMatugenTheme(fixture, "dark", { kittyOpacity: "invalid" }).value.tokens.surface_panel, "#ff101820");
assert.equal(result.value.tokens.scrim, "#99000000");
assert.equal(result.value.tokens.shadow, "#80000000");
assert.equal(result.value.tokens.highlight, "#513a5e");
assert.equal(result.value.tokens.on_highlight, "#f2daff");
assert.equal(result.value.tokens.success, "#b5c9e2");
assert.equal(result.value.tokens.charging, "#9ecaff");
assert.equal(result.value.tokens.warning, "#d5bce5");

const actualV4 = JSON.parse(await readFile(new URL("../fixtures/matugen/actual-v4.json", import.meta.url), "utf8"));
const actualResult = mapMatugenTheme(actualV4, "dark");
assert.equal(actualResult.ok, true, actualResult.errors.join("; "));
assert.equal(actualResult.value.tokens.primary, "#9ecaff");
assert.equal(actualResult.value.tokens.surface_hover, "#34414c");
const actualLightResult = mapMatugenTheme(actualV4, "light");
assert.equal(actualLightResult.ok, true, actualLightResult.errors.join("; "));
assert.equal(actualLightResult.value.tokens.surface_container_lowest, "#ffffff");
assert.equal(actualLightResult.value.tokens.surface_container_low, "#eef3f8");
assert.equal(actualLightResult.value.tokens.surface_container, "#e8eef5");
assert.equal(actualLightResult.value.tokens.surface_container_high, "#e2e8ef");
assert.equal(actualLightResult.value.tokens.surface_container_highest, "#dce2e9");
assert.equal(actualLightResult.value.tokens.surface_hover, "#f4f7fb");
assert.equal(actualLightResult.value.tokens.on_surface_subdued, "#3f4b56");
assert.equal(actualLightResult.value.tokens.on_surface_indicator, "#101820");
assert.equal(actualLightResult.value.tokens.on_surface_disabled, "#c1cbd6");
assert.equal(actualLightResult.value.tokens.on_surface_placeholder, "#717b86");

assert.equal(mapMatugenTheme({}, "dark").ok, false);
assert.equal(mapMatugenTheme(fixture, "sepia").ok, false);
const missing = structuredClone(fixture);
delete missing.colors.dark.primary;
assert.equal(mapMatugenTheme(missing, "dark").ok, false);
const missingSurfaceRole = structuredClone(fixture);
delete missingSurfaceRole.colors.dark.surface_bright;
assert.equal(mapMatugenTheme(missingSurfaceRole, "dark").ok, false);

console.log("matugen fixtures passed");
